import YoutubeLogo from "../../public/youtubeLogoDark.png";
import HomeIcon from "../../public/home.png";
import ShortsIcon from "../../public/shorts.png";
import SubscriptionIcon from "../../public/subs.png";
import SubscriptionIcon2 from "../../public/subs2.png";
import DegreeIcon from "../../public/degree.png";
import DownlaodIcon from "../../public/download.png";
import GameIcon from "../../public/game.png";
import HistoryIcon from "../../public/history.png";
import InfoIcon from "../../public/info.png";
import LikeIcon from "../../public/like.png";
import ReportIcon from "../../public/report.png";
import SettingIcon from "../../public/setting.png";
import TrophyIcon from "../../public/trophy.png";
import ClockIcon from "../../public/clock.png";
import FeedbackIcon from "../../public/feedback.png";
import PlaylistIcon from "../../public/playlist.png";
import PlayIcon from "../../public/play.png";
import MusicIcon from "../../public/music.png";
import NewsIcon from "../../public/news.png";

export const YOUTUBE_LOGO_PNG = YoutubeLogo;
export const HOME_ICON_PNG = HomeIcon;
export const SHORTS_ICON_PNG = ShortsIcon;
export const SUBSCRIPTIONS_ICON_PNG = SubscriptionIcon;
export const SUBSCRIPTIONS_ICON_PNG_2 = SubscriptionIcon2;
export const HISTORY_ICON_PNG = HistoryIcon;
export const GAME_ICON_PNG = GameIcon;
export const CLOCK_ICON_PNG = ClockIcon;
export const FEEDBACK_ICON_PNG = SubscriptionIcon2;
export const SETTING_ICON_PNG = SubscriptionIcon2;
export const REPORT_ICON_PNG = SubscriptionIcon2;
export const INFO_ICON_PNG = SubscriptionIcon2;
export const TROPHY_ICON_PNG = TrophyIcon;
export const LIKE_ICON_PNG = LikeIcon;
export const DEGREE_ICON_PNG = DegreeIcon;
export const DOWNLAOD_ICON_PNG = DownlaodIcon;
export const PLAYLIST_ICON_PNG = PlaylistIcon;
export const PLAY_ICON_PNG = PlayIcon;
export const MUSIC_ICON_PNG = MusicIcon;
export const NEWS_ICON_PNG = NewsIcon;
